from enum import Enum


class CountryCode(str, Enum):
    """ISO 3166-1 alpha-3 country codes plus custom codes"""

    ALB = "Albania"
    ARE = "United Arab Emirates"
    ARG = "Argentina"
    AUS = "Australia"
    AUT = "Austria"
    BEBRU = "Belgium - Brussels Capital"
    BEFED = "Belgium - Federal government"
    BEL = "Belgium"
    BEVLG = "Belgium - Flanders"
    BEWAL = "Belgium - Wallonia"
    BEWBF = "Belgium - Wallonia-Brussels Federation"
    BGR = "Bulgaria"
    BIH = "Bosnia and Herzegovina"
    BRA = "Brazil"
    CAN = "Canada"
    CHE = "Switzerland"
    CHL = "Chile"
    CHN = "China"
    COL = "Colombia"
    CRI = "Costa Rica"
    CYP = "Cyprus"
    CZE = "Czech Republic"
    DEU = "Germany"
    DNK = "Denmark"
    EGY = "Egypt"
    ESP = "Spain"
    EST = "Estonia"
    EU = "European Union"
    FIN = "Finland"
    FRA = "France"
    GBR = "United Kingdom"
    GRC = "Greece"
    HRV = "Croatia"
    HUN = "Hungary"
    IDN = "Indonesia"
    IND = "India"
    IRL = "Ireland"
    ISL = "Iceland"
    ISR = "Israel"
    ITA = "Italy"
    JPN = "Japan"
    KAZ = "Kazakhstan"
    KOR = "Korea"
    KOS = "Kosovo"
    LTU = "Lithuania"
    LUX = "Luxembourg"
    LVA = "Latvia"
    MEX = "Mexico"
    MKD = "Republic of North Macedonia"
    MLT = "Malta"
    MNE = "Montenegro"
    MYS = "Malaysia"
    NLD = "Netherlands"
    NOR = "Norway"
    NZL = "New Zealand"
    PER = "Peru"
    PHL = "Philippines"
    POL = "Poland"
    PRT = "Portugal"
    ROU = "Romania"
    RUS = "Russian Federation"
    SGP = "Singapore"
    SRB = "Serbia"
    SVK = "Slovak Republic"
    SVN = "Slovenia"
    SWE = "Sweden"
    THA = "Thailand"
    TUR = "Türkiye"
    UKR = "Ukraine"
    USA = "United States"
    VNM = "Viet Nam"
    ZAF = "South Africa"
    TST = "Test"  # For testing purposes

    @classmethod
    def is_valid(cls, code: str) -> bool:
        """Check if a country code is valid"""
        return code in cls.__members__
