affinityCookieTtlSec: 0
backends:
- balancingMode: RATE
  capacityScaler: 1.0
  group: https://www.googleapis.com/compute/v1/projects/windy-augury-442117-b9/zones/europe-west3-a/networkEndpointGroups/k8s1-e20c90b9-default-api-80-720bbe32
  maxRatePerEndpoint: 1.0
connectionDraining:
  drainingTimeoutSec: 60
creationTimestamp: '2024-11-30T17:34:36.696-08:00'
description: '{"kubernetes.io/service-name":"default/api","kubernetes.io/service-port":"\u0026ServiceBackendPort{Name:,Number:80,}","x-features":["NEG"]}'
enableCDN: false
fingerprint: Oake2xdZbMM=
healthChecks:
- https://www.googleapis.com/compute/v1/projects/windy-augury-442117-b9/global/healthChecks/k8s1-e20c90b9-default-api-80-720bbe32
id: '6391428526643741635'
kind: compute#backendService
loadBalancingScheme: EXTERNAL
logConfig:
  enable: true
  optionalMode: EXCLUDE_ALL_OPTIONAL
  sampleRate: 1.0
name: k8s1-e20c90b9-default-api-80-720bbe32
port: 80
portName: port0
protocol: HTTP
selfLink: https://www.googleapis.com/compute/v1/projects/windy-augury-442117-b9/global/backendServices/k8s1-e20c90b9-default-api-80-720bbe32
sessionAffinity: NONE
timeoutSec: 300
usedBy:
- reference: https://www.googleapis.com/compute/v1/projects/windy-augury-442117-b9/global/urlMaps/k8s2-um-xgbuul6z-default-api-ingress-ufv8p8w5
